# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '[nom_de_votre_fichier].ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


